/**
 * Claude API Integration — production AI backbone for RevOS.
 *
 * SECURITY: The Anthropic API key is kept server-side only.
 * When VITE_API_URL is set, the frontend proxies AI requests through
 * the backend /api/ai/prompt endpoint. Falls back to local
 * prompt-executor generators when no backend URL is configured.
 *
 * Architecture:
 *   1. Hydrate prompt template with deal/pipeline context
 *   2. POST to backend /api/ai/prompt (backend calls Claude with server-side key)
 *   3. Parse structured response into PromptOutput shape
 *   4. Return to consumer (DealAIAnalysis, AICopilot, MeetingPrep)
 */

import { executePrompt as localExecute, type PromptOutput, type OutputAction } from './prompt-executor';
import type { Deal } from '@/data/demo-data';
import { PROMPT_LIBRARY } from '@/data/prompt-library';
import { COMPETITORS } from '@/data/evercam-context';

// ---------------------------------------------------------------------------
// Config — NO API KEYS IN FRONTEND
// ---------------------------------------------------------------------------

const API_BASE = import.meta.env.VITE_API_URL || '';

function isLive(): boolean {
  return !!API_BASE;
}

// ---------------------------------------------------------------------------
// Context builders
// ---------------------------------------------------------------------------

function buildDealContext(deal: Deal): string {
  const comp = deal.competitor
    ? COMPETITORS.find(c => c.name.toLowerCase().includes(deal.competitor!.toLowerCase()))
    : null;

  return `## Deal Context
- Company: ${deal.company}
- ACV: €${deal.acv.toLocaleString()}
- Stage: ${deal.stage} (${deal.daysInStage} days)
- PQS: ${deal.pqScore} (Grade ${deal.grade})
- Segment: ${deal.segment}
- Product: ${deal.productBundle} (${deal.cameraCount} cameras)
- Forecast: ${deal.forecastCategory}
- Win probability: ${Math.round(deal.probabilities.win * 100)}%
- Slip probability: ${Math.round(deal.probabilities.slip * 100)}%
- Persona gaps: ${deal.personaGaps.length > 0 ? deal.personaGaps.join(', ') : 'None'}
- Missing steps: ${deal.missingSteps.length > 0 ? deal.missingSteps.join(', ') : 'None'}
- Price risk: ${Math.round(deal.priceRisk * 100)}%
- Competitor: ${comp ? `${comp.name} (win rate: ${Math.round(comp.evercamWinRate * 100)}%)` : 'None identified'}
- Next actions: ${deal.nextActions.join('; ')}
- ICP score: ${deal.icpScore}
- Close date: ${deal.closeDate}`;
}

// ---------------------------------------------------------------------------
// Backend proxy call (API key stays server-side)
// ---------------------------------------------------------------------------

async function callBackendAI(userPrompt: string, maxTokens = 2048): Promise<string> {
  const res = await fetch(`${API_BASE}/api/ai/prompt`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    credentials: 'include',
    body: JSON.stringify({ prompt: userPrompt, maxTokens }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`AI API ${res.status}: ${err}`);
  }

  const data = await res.json();
  return data.content || '';
}

// ---------------------------------------------------------------------------
// Parse actions from AI markdown response
// ---------------------------------------------------------------------------

function extractActions(content: string, deal?: Deal): OutputAction[] {
  const actions: OutputAction[] = [];

  if (deal) {
    if (content.includes('Economic Buyer') && content.includes('meeting')) {
      actions.push({
        id: `act_${deal.id}_eb_${Date.now()}`,
        label: `Schedule EB meeting for ${deal.company}`,
        type: 'crm-task',
        dealId: deal.id,
        payload: 'AI-recommended: Schedule Economic Buyer meeting',
      });
    }
    if (content.includes('Stall Breaker') || content.includes('re-engage')) {
      actions.push({
        id: `act_${deal.id}_stall_${Date.now()}`,
        label: 'Trigger Stall Breaker play',
        type: 'coaching-play',
        dealId: deal.id,
        payload: 'Stall Breaker coaching play',
      });
    }
    actions.push({
      id: `act_${deal.id}_note_${Date.now()}`,
      label: `Push analysis to Zoho`,
      type: 'crm-note',
      dealId: deal.id,
      payload: 'AI analysis generated by RevOS',
    });
  }

  return actions;
}

// ---------------------------------------------------------------------------
// Public API — drop-in replacement for local prompt executor
// ---------------------------------------------------------------------------

export async function executePrompt(
  promptId: string,
  deal?: Deal,
  repName?: string,
): Promise<PromptOutput> {
  if (!isLive()) {
    return localExecute(promptId, deal, repName);
  }

  const prompt = PROMPT_LIBRARY.find(p => p.id === promptId);
  const promptName = prompt?.name || promptId;

  let userMessage = '';
  if (prompt) {
    userMessage += `## Task\n${prompt.name}\n\nCategory: ${prompt.category}\nFunnel Stage: ${prompt.funnelStage}\n\n`;
  }
  if (deal) {
    userMessage += buildDealContext(deal) + '\n\n';
  }
  if (repName) {
    userMessage += `## Rep Context\nPrepare 1:1 coaching agenda for rep: ${repName}\n\n`;
  }

  userMessage += `\nProvide your analysis in structured markdown. Include specific recommendations with reasoning. Reference deal metrics and scores.`;

  try {
    const content = await callBackendAI(userMessage);
    const actions = extractActions(content, deal);

    return {
      promptId,
      promptName,
      generatedAt: new Date(),
      dealContext: deal ? { id: deal.id, company: deal.company } : undefined,
      content,
      actions,
      confidence: 0.92,
      dataSourcesUsed: ['Claude AI', 'Pipeline Data', 'Evercam Context', ...(deal ? ['Deal Signals'] : [])],
    };
  } catch (err) {
    console.warn('[RevOS] AI API call failed, falling back to local executor:', err);
    return localExecute(promptId, deal, repName);
  }
}

/**
 * Free-form chat query — for the AI Copilot.
 */
export async function chatQuery(
  query: string,
  context?: { deals?: Deal[]; role?: string; page?: string },
): Promise<{ content: string; actions: OutputAction[] }> {
  if (!isLive()) {
    return { content: '', actions: [] };
  }

  let userMessage = `User query: "${query}"\n\n`;
  if (context?.role) userMessage += `User role: ${context.role}\n`;
  if (context?.page) userMessage += `Current page: ${context.page}\n`;
  if (context?.deals) {
    const summary = context.deals.slice(0, 10);
    userMessage += `\nTop pipeline deals:\n${summary.map(d =>
      `- ${d.company}: €${d.acv.toLocaleString()}, ${d.stage}, PQS ${d.pqScore} (${d.grade})`
    ).join('\n')}\n`;
  }

  userMessage += `\nProvide a helpful, data-driven response. If you reference specific deals, include their metrics. Suggest concrete next steps.`;

  const content = await callBackendAI(userMessage, 1024);
  return { content, actions: [] };
}

export { isLive as isClaudeConfigured };
